name: 'Docker Action Recipe by Johanny'
description: 'Greet someone'
branding:
  icon: arrow-up-right
  color: green
author: 'Johanny'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  answer:
    description: 'The answer to everything (always 42)'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
